# Generated by Django 3.1.2 on 2020-11-01 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
            },
        ),
        migrations.CreateModel(
            name='CandidateTimeSlot',
            fields=[
                ('timeslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interview_slots.timeslot')),
                ('candidate_name', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'verbose_name': 'Candidate Time Slot',
                'verbose_name_plural': 'Candidate Time Slots',
            },
            bases=('interview_slots.timeslot',),
        ),
        migrations.CreateModel(
            name='InterviewerTimeSlot',
            fields=[
                ('timeslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interview_slots.timeslot')),
                ('interviewer_name', models.CharField(blank=True, max_length=180, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_candidate_time_slot', to='interview_slots.candidatetimeslot')),
            ],
            options={
                'verbose_name': 'Interviewer Time Slot',
                'verbose_name_plural': 'Interviewer Time Slots',
            },
            bases=('interview_slots.timeslot',),
        ),
    ]
